### PR TITLE
Revert "Revert "App backscaling on demand (#458)" (#497)"

### PR DESCRIPTION
**Pull request by jmontleon**
This reverts commit 814bf46d82eba35e670186be410ecf64af971f38 and restores backscaling.

This can be merged once https://github.com/konveyor/mig-operator/pull/303 is updated to include missing permissions and gets merged. Missing permissions are at least the following. I'm a little concerned we'll hit other custom verbs on other resources we hit with velero as well including builds, and velero/migration CRDs, but I don't have a workload to test migrating for builds and my suspicion is the CRDs were unique to velero. 

If we end up seeing the same with builds we'll have to add `build.openshift.io` to the apiGroups here too.

```
diff --git a/deploy/olm-catalog/konveyor-operator/v1.2.0/konveyor-operator.v1.2.0.clusterserviceversion.yaml b/deploy/olm-catalog/konveyor-operator/v1.2.0/konveyor-operator.v1.2.0.clusterserviceversion.yaml
index fe43df7..1d6cdee 100644
--- a/deploy/olm-catalog/konveyor-operator/v1.2.0/konveyor-operator.v1.2.0.clusterserviceversion.yaml
+++ b/deploy/olm-catalog/konveyor-operator/v1.2.0/konveyor-operator.v1.2.0.clusterserviceversion.yaml
@@ -589,6 +589,12 @@ spec:
           - update
           - delete
           - deletecollection
+        - apiGroups:
+          - rbac.authorization.k8s.io
+          resources:
+          - '*'
+          verbs:
+          - '*'
       - serviceAccountName: velero
         rules:
         - apiGroups:
diff --git a/roles/migrationcontroller/templates/mig_rbac.yml.j2 b/roles/migrationcontroller/templates/mig_rbac.yml.j2
index f429411..d14b3c9 100644
--- a/roles/migrationcontroller/templates/mig_rbac.yml.j2
+++ b/roles/migrationcontroller/templates/mig_rbac.yml.j2
@@ -209,6 +209,12 @@ rules:
   - delete
   - update
   - deletecollection
+- apiGroups:
+  - rbac.authorization.k8s.io
+  resources:
+  - '*'
+  verbs:
+  - '*'
 ---
 apiVersion: v1
 kind: ServiceAccount

### CODE REVIEW

**Comment by Danil-Grigorev** [comment]
Merge together with PR: https://github.com/konveyor/mig-operator/pull/303

**Comment by djwhatle** [comment]
\test-with-operator

**Comment by djwhatle** [comment]
\test-with-operator 303

**Comment by djwhatle** [comment]
\test-with-operator 303

**Pull request merged**
