### PR TITLE
Bug 2064739: Increase Liveness and Readiness probe timeouts

### PR DESCRIPTION
**Pull request by jmontleon**

### CODE REVIEW

**Review by rayfordj — APPROVED** [review]
/lgtm

**Comment by rayfordj** [comment]
@jmontleon , FYI, the pr-bz automation is broken.  I only just noticed it for this PR. It's isn't going to handle the expected BZ **Status:** transitions for us at the moment.

**Review by pranavgaikwad — APPROVED** [review]

**Comment by eriknelson** [comment]
@rayfordj @shawn-hurley is this the result of that robot account getting deprovisioned?

**Comment by rayfordj** [comment]
> @rayfordj @shawn-hurley is this the result of that robot account getting deprovisioned?

@eriknelson , I need to research to confirm; off the top of my head it appears a change in API for auth.  I've taken an action-item for this, but haven't investigated any further than reading the error...

```
&bugzilla.requestError{statusCode:200, bugzillaCode:32000, message:"You have
attempted to access the API either using an unsupported method or using one or
more unsupported parameters. You must use the 'Authorization' header to
authenticate to the API and you must remove all unsupported parameters from
the query. The unsupported parameters are: Bugzilla_login, Bugzilla_password,
Bugzilla_token, Bugzilla_api_key. See
https://bugzilla.redhat.com/docs/en/html/api/core/v1/general.html#authentication
for details on using the 'Authorization' header."}

```

**Pull request merged**
