### PR TITLE
Fix 'make run' on macOS

### PR DESCRIPTION
**Pull request by jwmatthews**
Fixes issue #915

### CODE REVIEW

**Review by shawn-hurley — APPROVED** [review]
LGTM

ran on my mac and works as expected

**Comment by djwhatle** [comment]
@jwmatthews I've been building on macOS for a while with the current build tags, it's interesting that you needed this.

Do you use bash?
Here's what I'm running for comparison.

```
bash --version
GNU bash, version 5.0.17(1)-release (x86_64-apple-darwin19.4.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by jwmatthews** [comment]
Below is what I'm running.

macOS Catalina 10.15.7
```
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.
```

I had success with 'make', it'd compiled the binary fine as-is.
Issue was seen with 'make run'.

The 'make run' wasn't passing through the BUILDTAGS info which caused the build with 'go run' to fail.

**Review by djwhatle — APPROVED** [review]
Worked for me, ACK

**Comment by ibolton336** [comment]
I was also seeing this on fedora 33 with make version 4.3.

**Pull request merged**
