### PR TITLE
[BUG 1881254]: exclude imagestreamtags from stage and imagestreams initial backup

### PR DESCRIPTION
**Pull request by alaypatel07**

### CODE REVIEW

**Comment by alaypatel07** [comment]
I'll create a BZ and add this, this needs to go in 1.3.0

**Review by sseago — APPROVED** [review]
This looks right, assuming everything works with testing.

**Comment by alaypatel07** [comment]
\test

**Comment by alaypatel07** [comment]
```
$  oc get imagestreamtags -n image-benchmark | grep 'docker\.io'
my-ruby:latest                       docker.io/openshift/ruby-20-centos7@sha256:751a3cd1905914389fe568c25b3d5367cd705a0e4f81970a361f670ce891baf7                                       2 months ago
ruby:2.0                             docker.io/openshift/ruby-20-centos7@sha256:751a3cd1905914389fe568c25b3d5367cd705a0e4f81970a361f670ce891baf7                                       2 months ago
ruby-hello-world:alias               docker.io/alaypatel07/ruby-hello-world@sha256:c595d4756720868b8ca72d0293751fb54e5ae6f4aa41826e4a356e27340e8604                                    2 months ago
ruby-hello-world:latest              docker.io/alaypatel07/ruby-hello-world@sha256:c595d4756720868b8ca72d0293751fb54e5ae6f4aa41826e4a356e27340e8604                                    2 months ago
ruby-hello-world:static-tag          docker.io/alaypatel07/ruby-hello-world@sha256:8c392e72bdcf42cb3d051007797d7272c42934594da18d42ddce8d40bd99e6b6                                    2 months ago
ruby-hello-world:static-tag-latest   docker.io/alaypatel07/ruby-hello-world@sha256:173646699fdcfe7c1bca741cb545cf4409046dc2315898466533db694da2d2b5                                    2 months ago
ssh-rsync:latest                     docker.io/alaypatel07/ssh-rsync@sha256:c72e66e59bfbe7cd236e04eee617569fb9255993ddcb046f268778b120836e4e                                           2 months ago
[alpatel@alpatel mig-controller]$
```

Source has imagestreamtags pointing to external images

run a stage migration

on destination
```
[alpatel@alpatel mig-controller]$ oc logs  velero-6bb4cffbd4-jpd5b | grep 473442a0-fc72-11ea-96e9-1f302c233adc-ljwww | grep istag-restore
[alpatel@alpatel mig-controller]$
[alpatel@alpatel mig-controller]$  oc get imagestreamtags -n image-benchmark | grep 'docker\.io'
[alpatel@alpatel mig-controller]$
```

**Comment by alaypatel07** [comment]
I ran a final migration and was able to see time imagestreamtags getting created

```
$ oc get imagestreamtags -n image-benchmark | grep "docker.io"
my-ruby:latest                       docker.io/openshift/ruby-20-centos7@sha256:751a3cd1905914389fe568c25b3d5367cd705a0e4f81970a361f670ce891baf7                                                       About an hour ago
ruby:2.0                             docker.io/openshift/ruby-20-centos7@sha256:751a3cd1905914389fe568c25b3d5367cd705a0e4f81970a361f670ce891baf7                                                       About an hour ago
ruby-hello-world:static-tag-latest   docker.io/alaypatel07/ruby-hello-world@sha256:173646699fdcfe7c1bca741cb545cf4409046dc2315898466533db694da2d2b5                                                    About an hour ago
ruby-hello-world:alias               docker.io/alaypatel07/ruby-hello-world@sha256:c595d4756720868b8ca72d0293751fb54e5ae6f4aa41826e4a356e27340e8604                                                    About an hour ago
ruby-hello-world:latest              docker.io/alaypatel07/ruby-hello-world@sha256:c595d4756720868b8ca72d0293751fb54e5ae6f4aa41826e4a356e27340e8604                                                    About an hour ago
ruby-hello-world:static-tag          docker.io/alaypatel07/ruby-hello-world@sha256:8c392e72bdcf42cb3d051007797d7272c42934594da18d42ddce8d40bd99e6b6                                                    About an hour ago
ssh-rsync:latest                     docker.io/alaypatel07/ssh-rsync@sha256:c72e66e59bfbe7cd236e04eee617569fb9255993ddcb046f268778b120836e4e                                                           About an hour ago
```

**Comment by sseago** [comment]
@alaypatel07 Looks good to me. Feel free to merge and cherry-pick to release-1.3.0 when you're ready.

**Pull request merged**
