### PR TITLE
Bug 1882409: Hook job and pod should get purged when migration is cancelled.

### PR DESCRIPTION
**Pull request by seshapad**
Signed-off-by: seshapad <seshapad@in.ibm.com>

### CODE REVIEW

**Comment by djwhatle** [comment]
Thanks for the PR @seshapad ! I just made a commit moving `stopHookJobs` to its own phase in task.go and added it to the `CancelItinerary`. I'll give this a try now.

**Comment by seshapad** [comment]
> Thanks for the PR @seshapad ! I just made a commit moving `stopHookJobs` to its own phase in task.go and added it to the `CancelItinerary`. I'll give this a try now.

@djwhatle Thank you for your changes! Having my fingers crossed that it works out!

**Review by djwhatle — APPROVED** [review]
I was able to verify that this PR works as expected.

I simulated a stalled hook with the following playbook

```
- hosts: localhost
  gather_facts: false
  tasks:
  - shell: sleep infinity
```

I set this up as a Prebackup Hook, and when I canceled the migration the hook was deleted. Thanks again @seshapad 👍

**Review by jmontleon — APPROVED** [review]
ACK. Thank you!

**Pull request merged**
