### PR TITLE
Revert "App backscaling on demand (#458)"

### PR DESCRIPTION
**Pull request by jmontleon**
This reverts commit e5e73fd6c585ee18adde3f3b3b1dcc6e79af35e9.

### CODE REVIEW

**Comment by jmontleon** [comment]
I would like to revert this until the mig-operator PR for permissions and CRDs is complete.

**Comment by Danil-Grigorev** [comment]
@jmontleon Are you sure it is not an issue with your local setup?

**Comment by jmontleon** [comment]
Images were from quay.io/konveyor/*:latest tags. The metadata was rebuilt and pushed using up to the konveyor org using up to date usptream/master. I confirmed earlier this morning it includes your permission changes from PR 293. I don't know what you mean by 'local setup'. I used two AWS clusters I have been using for the last several weeks to perform the migration,

**Comment by jmontleon** [comment]
I left notes on https://github.com/konveyor/mig-controller/pull/498 on what's missing. You can see 'admin' missing in the errors I linked:

https://paste.centos.org/view/c9994b38
```
{"level":"error","ts":1587072324.2251916,"logger":"migration|nm5th","msg":"","migration":"40a09600-8026-11ea-84ce-6b5545abd27f","error":"rolebindings.rbac.authorization.k8s.io \"admin\" is forbidden: user \"system:serviceaccount:openshift-migration:migration-controller\"
```

Stacktrace also seems to indicate it's coming from `github.com/konveyor/mig-controller/pkg/controller/migmigration.(*Task).deleteLabels`
```
"stacktrace":"github.com/konveyor/mig-controller/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/konveyor/mig-controller/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/konveyor/mig-controller/pkg/logging.Logger.Error\n\t/go/src/github.com/konveyor/mig-controller/pkg/logging/logger.go:75\ngithub.com/konveyor/mig-controller/pkg/logging.Logger.Trace\n\t/go/src/github.com/konveyor/mig-controller/pkg/logging/logger.go:81\ngithub.com/konveyor/mig-controller/pkg/controller/migmigration.(*Task).deleteLabels\n\t/go/src/github.com/konveyor/mig-controller/pkg/controller/migmigration/annotation.go:521\ngithub.com/konveyor/mig-controller/pkg/controller/migmigration.(*Task).Run\n\t/go/src/github.com/konveyor/mig-controller/pkg/controller/migmigration/task.go:516\ngithub.com/konveyor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).migrate\n\t/go/src/github.com/konveyor/mig-controller/pkg/controller/migmigration/migrate.go:78\ngithub.com/konveyor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).Reconcile\n\t/go/src/github.com/konveyor/mig-controller/pkg/controller/migmigration/migmigration_controller.go:195\ngithub.com/konveyor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/konveyor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/konveyor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/konveyor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/konveyor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/konveyor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/konveyor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/konveyor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/konveyor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/konveyor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

**Comment by Danil-Grigorev** [comment]
@jmontleon I'm (accidentally) running two 4.4 clusters when I tried to reproduce the issue you saw. Both on AWS, one of them is hosting controller via OLM:latest (I deployed it before revert) and another non-olm latest. I'm going to try it with both OLM installations now in order to see.

I'm curious, all I added with this PR, is a couple of `Update` `Delete` and `DeleteCollection` requests. The operator PR added permissions to do that for `wildcard` resources. How is `rolebindings.rbac.authorization.k8s.io \"admin\"` is involved here?..

**Comment by jmontleon** [comment]
Following the trace it looks like it's coming from:
https://github.com/konveyor/mig-controller/pull/498/files#diff-a87df49e0b6b3be1f807dbaaef3c0c7aR514-R523

So it looks like it's coming from the Update. Is this just deleting labels? Either way, perhaps updating a rolebinding is not permissable without admin?

**Comment by jmontleon** [comment]
I do have a rolebinding in my ns that appears to have been restored:

**Comment by jmontleon** [comment]
To get the admin rolebinding run `oc new-project foo` instead of `oc create namespace`. new-project will create it, create namespace will not.

**Pull request merged**
