### PR TITLE
MIG-323 - Minor logging improvements to migstorage_controller 

### PR DESCRIPTION
**Pull request by shubham-pampattiwar**
This adds minor logging updates to the migstorage_controller based on feedback received in https://github.com/konveyor/mig-controller/pull/731

### CODE REVIEW

**Review by alaypatel07 — APPROVED** [review]
ACK

**Review by djwhatle — COMMENTED** [review]
@shubham-pampattiwar is this PR just reducing line lengths?

**Comment by shubham-pampattiwar** [comment]
> @shubham-pampattiwar is this PR just reducing line lengths?

@djwhatle And some cosmetic updates like `subject` to `subject:`, addition of periods and some formatting.

**Review by djwhatle — APPROVED** [review]

**Review by alaypatel07 — APPROVED** [review]
ACK

**Pull request merged**
