### PR TITLE
Don't count resources that won't be migrated

### PR DESCRIPTION
**Pull request by jmontleon**

### CODE REVIEW

**Comment by jmontleon** [comment]
No BZ for this yet but I expect QE is going to ask for this so getting it ready.

**Review by djwhatle — APPROVED** [review]

**Comment by djwhatle** [comment]
@jmontleon did a BZ ever show up for this ? Seems like something we should merge regardless no?

**Comment by djwhatle** [comment]
@jmontleon can we merge this?

**Comment by jmontleon** [comment]
@djwhatle I don't think I ever saw a BZ but would be fine merging it for a future release.

**Comment by djwhatle** [comment]
Merging.

**Pull request merged**
