### PR TITLE
Add direct migration resources to debug view

### LINKED ISSUE #847: [MIG-454] Enable Direct Migration resources to be viewed in debug mode

### PR DESCRIPTION
**Pull request by dymurray**
Fixes #847

### CODE REVIEW

**Comment by dymurray** [comment]
Screenshot from 2021-01-04 16-46-52

**Review by djwhatle — COMMENTED** [review]
Changes look sane, going to give this a try now.

**Comment by djwhatle** [comment]
@dymurray seeing this error emitted from mig-controller when the UI is open.

```
{"level":"error","ts":1609870301.324758,"logger":"discovery|686dn","msg":"","error":"no matches for kind \"DirectVolumeMigration\" in version \"migration.openshift.io/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error
	/Users/dwhatley/code/go/pkg/mod/github.com/go-logr/zapr@v0.3.0/zapr.go:132
github.com/konveyor/controller/pkg/logging.Logger.Error
	/Users/dwhatley/code/go/pkg/mod/github.com/konveyor/controller@v0.2.1/pkg/logging/logger.go:92
github.com/konveyor/controller/pkg/logging.Logger.Trace
	/Users/dwhatley/code/go/pkg/mod/github.com/konveyor/controller@v0.2.1/pkg/logging/logger.go:98
github.com/konveyor/mig-controller/pkg/controller/discovery/container.(*Container).Add
	/Users/dwhatley/code/go/src/github.com/konveyor/mig-controller/pkg/controller/discovery/container/container.go:88
github.com/konveyor/mig-controller/pkg/controller/discovery.(*ReconcileDiscovery).Reconcile
	/Users/dwhatley/code/go/src/github.com/konveyor/mig-controller/pkg/controller/discovery/controller.go:157
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/Users/dwhatley/code/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.11/pkg/internal/controller/controller.go:215
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/Users/dwhatley/code/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.11/pkg/internal/controller/controller.go:158
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/Users/dwhatley/code/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/Users/dwhatley/code/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:134
k8s.io/apimachinery/pkg/util/wait.Until
	/Users/dwhatley/code/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:88"}
```

**Review by djwhatle — CHANGES_REQUESTED** [review]
Error needs resolving

**Review by djwhatle — APPROVED** [review]
Worked for me. Thanks @dymurray

**Pull request merged**
