### PR TITLE
Switching mig-controller to go mod

### LINKED ISSUE #438: [MIG-399] Use go modules
From golang 1.14 modules are defacto standard

### PR DESCRIPTION
**Pull request by shawn-hurley**
* Having to set specific values to keep compatability
* pinning is done w/ replaces

fixes #438

### CODE REVIEW

**Comment by djwhatle** [comment]
@shawn-hurley based on the number of lines removed, I'm guessing this removes `vendor`.

@jmontleon @rayfordj will this work for you guys?

**Comment by sseago** [comment]
Running `go mod vendor` should restore the vendored files. We need vendor for downstream builds -- we already confronted the issue with openshift-velero-plugin.

**Comment by sseago** [comment]
We've done the same thing with our velero fork for similar reasons (velero upstream has recently moved to modules). We also had to update the `go build` line in velero with `-mod=vendor`.

**Comment by djwhatle** [comment]
I'm hitting an error trying to `make run`

Do I need to have $GOROOT set to something in particular for go mod builds to work? I don't have $GOROOT set to anything currently.

```
make run
./hack/conversion-gen-`go env GOOS` --go-header-file ./hack/boilerplate.go.txt --output-file-base zz_conversion_generated -i github.com/konveyor/mig-controller/pkg/compat/conversion/...
W1118 16:17:06.783441    4997 parse.go:227] Ignoring directory github.com/konveyor/mig-controller/pkg/compat/conversion: unable to import "github.com/konveyor/mig-controller/pkg/compat/conversion": go/build: importGo github.com/konveyor/mig-controller/pkg/compat/conversion: exit status 2
go: cannot find GOROOT directory: /usr/lib/golang

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12d5535]

goroutine 1 [running]:
k8s.io/gengo/parser.(*Builder).AddDirRecursive(0xc0000a9400, 0xc000018300, 0x38, 0x1, 0xc0000bddf8)
	/home/dgrigore/go/pkg/mod/k8s.io/gengo@v0.0.0-20200114144118-36b2048a9120/parser/parse.go:232 +0xb5
k8s.io/gengo/args.(*GeneratorArgs).NewBuilder(0xc0000dd9a0, 0xc0000bde90, 0x12e518d, 0x134b160)
	/home/dgrigore/go/pkg/mod/k8s.io/gengo@v0.0.0-20200114144118-36b2048a9120/args/args.go:143 +0x21a
k8s.io/gengo/args.(*GeneratorArgs).Execute(0xc0000dd9a0, 0xc0000e8a20, 0x13ae330, 0x6, 0x13dba90, 0xc00000c7e0, 0x1)
	/home/dgrigore/go/pkg/mod/k8s.io/gengo@v0.0.0-20200114144118-36b2048a9120/args/args.go:192 +0x3c
main.main()
	/home/dgrigore/go/src/github.com/kubernetes/code-generator/cmd/conversion-gen/main.go:117 +0x2fe
make: *** [conversion-gen] Error 2
```

**Comment by shawn-hurley** [comment]
@djwhatle I don't know what is going on there seems like something is not right. 

```
 shurley@unknown1866da2d6348  ~/repos/konveyor/mig-controller   switch-gomod ±  make conversion-gen
which: no controller-gen in (/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/shurley/bin:/home/shurley/bin)
./hack/conversion-gen-`go env GOOS` --go-header-file ./hack/boilerplate.go.txt --output-file-base zz_conversion_generated -i github.com/konveyor/mig-controller/pkg/compat/conversion/...
```

and I can also attempt to run the actual file here

```
$ ./hack/conversion-gen-$(go env GOOS) --go-header-file ./hack/boilerplate.go.txt --output-file-base zz_conversion_generated -i github.com/konveyor/mig-controller/pkg/compat/conversion/...
 shurley@unknown1866da2d6348  ~/repos/konveyor/mig-controller   switch-gomod ±  echo $GOROOT

 shurley@unknown1866da2d6348  ~/repos/konveyor/mig-controller   switch-gomod ±  echo $GOBIN
/home/shurley/go/bin
 shurley@unknown1866da2d6348  ~/repos/konveyor/mig-controller   switch-gomod ±  which golang
/usr/bin/which: no golang in (/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/shurley/bin:/home/shurley/bin)
 ✘ shurley@unknown1866da2d6348  ~/repos/konveyor/mig-controller   switch-gomod ±  which go
/usr/bin/go
```

**Comment by shawn-hurley** [comment]
1. Doc new CRD name/generation location
2. operator PR
3. Test CRD's w/ 3.7

**Comment by djwhatle** [comment]
@shawn-hurley and I discussed, we think it would be best to wait on merge until 1.4.0 is out the door so that we don't complicate the 1.4.0 release and have time to test the CRD changes. This PR does bump controller-tools to a significantly newer version, so the auto-generated CRDs have significant changes.

**Actions needed before merge:**
- We need a mig-operator PR containing these CRD changes before we can merge this PR.
- We need to update hacking.md with new requirements (drop the requirement for dep, let people know if they need to set up something new like $GOBIN)
- Need to verify new CRDs work with an OCP 3.7 cluster (oldest supported version)

**Comment by shawn-hurley** [comment]
https://github.com/konveyor/mig-operator/pull/518 - operator PR to merge with this

**Pull request merged**
